services:
  jupyter:
    build: .
    ports:
      - "${Jupyter_Port}:${Jupyter_Port}"
    volumes:
      - "./notebooks/:/home/jovyan/notebooks/"
      - "./data/:/home/jovyan/data/"
    entrypoint: "jupyter lab -p=${Jupyter_Port}"
